In [24]:
import torch
print(torch.__version__)

1.4.0


$y = \theta_1x + \theta_0$
<br>
$\theta_1 = 0.6, \theta_0 = -44$

대충 내가 가진 데이터로 계산을 해보니

In [25]:
import torch.nn as nn

simple_regression = nn.Linear(1, 1, bias=True)
print(simple_regression)

Linear(in_features=1, out_features=1, bias=True)


In [26]:
init_weight = simple_regression.weight
init_bias = simple_regression.bias

print(init_weight)
print(init_bias)

print(init_weight.size())
print(init_bias.size())

Parameter containing:
tensor([[-0.5959]], requires_grad=True)
Parameter containing:
tensor([-0.7601], requires_grad=True)
torch.Size([1, 1])
torch.Size([1])


In [27]:
my_weight = torch.tensor([0.6666], dtype=torch.float).reshape_as(init_weight)
my_bias = torch.tensor([-44], dtype=torch.float).reshape_as(init_bias)

new_weight = nn.Parameter(my_weight)
new_bias = nn.Parameter(my_bias)

simple_regression.weight = new_weight
simple_regression.bias = new_bias

print(simple_regression.weight)
print(simple_regression.bias)

Parameter containing:
tensor([[0.6666]], requires_grad=True)
Parameter containing:
tensor([-44.], requires_grad=True)


In [28]:
cm = [174, 180, 169, 171]
kg = [ 72,  76,  65,  68]

data_x = torch.tensor(cm, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)
data_y = torch.tensor(kg, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)

with torch.no_grad():
    kg_prediction = simple_regression(data_x)

print(kg_prediction.reshape(1,-1))
print(data_y.reshape(1,-1))

tensor([[71.9884, 75.9880, 68.6554, 69.9886]])
tensor([[72., 76., 65., 68.]])


In [1]:
import seaborn as sns
sns.set_theme(color_codes=True)

plot1 = sns.regplot(x=cm, y=kg)
plot1.set(xlabel='cm', ylabel='kg')

AttributeError: module 'seaborn' has no attribute 'set_theme'

$$
\hat{\theta} = (\text{X}^T\cdot X)^{-1} \cdot \text{X}^T\cdot y
$$

\begin{aligned}
& (1)\qquad (\text{X}^T\cdot \text{X})^{-1}   \\
& (2)\qquad (1)\cdot \text{X}^T  \\ 
& (3)\qquad (2)\cdot y\\
\end{aligned}

In [83]:
cm = [174, 180, 169, 171] # x
kg = [ 72,  76,  65,  68] # y

# cm = [174, 180] # x
# kg = [ 72,  76]

data_x = torch.tensor(cm, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)
data_y = torch.tensor(kg, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)

print(data_x, data_x.size())
print(data_y, data_y.size())

def dot(a,b):
    return torch.matmul(a,b)

X = torch.cat((torch.ones_like(data_x), data_x,), 1)
y = data_y


dot1 = torch.inverse(dot(X.T, X))
dot2 = dot(dot1, X.T)
dot3 = dot(dot2, y)
dot3

tensor([[174.],
        [180.],
        [169.],
        [171.]]) torch.Size([4, 1])
tensor([[72.],
        [76.],
        [65.],
        [68.]]) torch.Size([4, 1])


tensor([[-99.4848],
        [  0.9784]])

In [85]:
X

tensor([[  1., 174.],
        [  1., 180.],
        [  1., 169.],
        [  1., 171.]])

In [84]:
torch.ones_like(data_x)

tensor([[1.],
        [1.],
        [1.],
        [1.]])