# Master Pytorch
- Practice Pytorch with document
https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/index.html

## Tensors

In [5]:
from __future__ import print_function
import torch

In [9]:
x = torch.Tensor(5,3)
print(x)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [14]:
x = torch.rand(5,3)
x

tensor([[0.3333, 0.0220, 0.0405],
        [0.2814, 0.1124, 0.3245],
        [0.5915, 0.0770, 0.4858],
        [0.4349, 0.9838, 0.2955],
        [0.8653, 0.4659, 0.2984]])


In [37]:
x.size()

torch.Size([5, 3])

## Operations

In [38]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x, '\n')
print(y, '\n')
x+y

tensor([[0.0430, 0.6802, 0.8324],
        [0.5913, 0.2868, 0.8106],
        [0.8894, 0.1749, 0.9243],
        [0.9474, 0.1537, 0.0626],
        [0.8357, 0.9545, 0.8140]]) 

tensor([[0.9284, 0.8741, 0.5335],
        [0.3748, 0.3481, 0.0538],
        [0.1679, 0.5142, 0.6381],
        [0.3811, 0.5227, 0.0127],
        [0.2731, 0.7837, 0.8613]]) 



tensor([[0.9713, 1.5544, 1.3659],
        [0.9661, 0.6348, 0.8644],
        [1.0573, 0.6891, 1.5624],
        [1.3285, 0.6765, 0.0753],
        [1.1088, 1.7382, 1.6753]])

In [39]:
torch.add(x,y)

tensor([[0.9713, 1.5544, 1.3659],
        [0.9661, 0.6348, 0.8644],
        [1.0573, 0.6891, 1.5624],
        [1.3285, 0.6765, 0.0753],
        [1.1088, 1.7382, 1.6753]])

In [44]:
result = torch.Tensor(5,3)
torch.add(x,y, out = result)
result

tensor([[0.9713, 1.5544, 1.3659],
        [0.9661, 0.6348, 0.8644],
        [1.0573, 0.6891, 1.5624],
        [1.3285, 0.6765, 0.0753],
        [1.1088, 1.7382, 1.6753]])

In [51]:
y.add(x)

tensor([[0.9713, 1.5544, 1.3659],
        [0.9661, 0.6348, 0.8644],
        [1.0573, 0.6891, 1.5624],
        [1.3285, 0.6765, 0.0753],
        [1.1088, 1.7382, 1.6753]])

## Indexing

In [97]:
x = torch.Tensor(5,3)
x[:,1]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000])

In [89]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [94]:
z = x.view(16, -1)
z

tensor([[-0.3199],
        [ 0.0338],
        [ 1.3035],
        [ 0.8442],
        [-0.3583],
        [ 0.7365],
        [ 0.8919],
        [ 0.5954],
        [ 0.9193],
        [ 0.9984],
        [-0.5380],
        [ 1.0763],
        [-1.5621],
        [-1.5019],
        [-1.6953],
        [-1.0398]])

## Convert Tensor&Numpy

In [87]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

# New things I learned

### 1. from __future__ import print_function
- __future__를 통해 최신 python버젼의 function을 가져올 수 있다.
- 참고https://ddanggle.gitbooks.io/interpy-kr/ch21-Targeting-python.html
### 2. Reshaping tensor with view(-1, n)
- -1값이 들어갈 땐 n을 보고 reshape할 모양을 유추