# Master Pytorch
- Practice Pytorch with document https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/index.html

## Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [3]:
x = torch.rand(5, 3)
x

tensor([[0.3653, 0.2851, 0.4539],
        [0.7865, 0.4154, 0.7230],
        [0.8320, 0.2372, 0.0451],
        [0.7461, 0.5411, 0.9353],
        [0.0769, 0.6366, 0.8283]])

In [4]:
x.size()

torch.Size([5, 3])

## Operations

In [5]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x, '\n')
print(y, '\n')
x + y

tensor([[0.4315, 0.4458, 0.0776],
        [0.8118, 0.8856, 0.4554],
        [0.3551, 0.1528, 0.7774],
        [0.4904, 0.8085, 0.4985],
        [0.3538, 0.2099, 0.4909]]) 

tensor([[0.6088, 0.6802, 0.2395],
        [0.2505, 0.1066, 0.7710],
        [0.6167, 0.6073, 0.2537],
        [0.8049, 0.1498, 0.6676],
        [0.1455, 0.9392, 0.7729]]) 



tensor([[1.0403, 1.1260, 0.3171],
        [1.0623, 0.9922, 1.2264],
        [0.9718, 0.7601, 1.0311],
        [1.2953, 0.9584, 1.1661],
        [0.4993, 1.1491, 1.2637]])

In [6]:
torch.add(x, y)

tensor([[1.0403, 1.1260, 0.3171],
        [1.0623, 0.9922, 1.2264],
        [0.9718, 0.7601, 1.0311],
        [1.2953, 0.9584, 1.1661],
        [0.4993, 1.1491, 1.2637]])

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result

tensor([[1.0403, 1.1260, 0.3171],
        [1.0623, 0.9922, 1.2264],
        [0.9718, 0.7601, 1.0311],
        [1.2953, 0.9584, 1.1661],
        [0.4993, 1.1491, 1.2637]])

In [8]:
y.add(x)

tensor([[1.0403, 1.1260, 0.3171],
        [1.0623, 0.9922, 1.2264],
        [0.9718, 0.7601, 1.0311],
        [1.2953, 0.9584, 1.1661],
        [0.4993, 1.1491, 1.2637]])

## Indexing

In [9]:
x = torch.Tensor(5, 3)
x[:, 1]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000])

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
z = x.view(16, -1)
z

tensor([[ 0.0909],
        [-1.5938],
        [ 0.4389],
        [-0.3391],
        [ 0.8635],
        [-0.5614],
        [-2.1249],
        [-0.5697],
        [-0.1709],
        [ 0.8689],
        [ 0.4060],
        [ 0.6008],
        [ 0.5965],
        [ 0.8380],
        [-0.5773],
        [-0.1272]])

## Convert Tensor&Numpy

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# New things I learned

### 1. from __future__ import print_function
- __future__를 통해 최신 python버젼의 function을 가져올 수 있다.
- 참고https://ddanggle.gitbooks.io/interpy-kr/ch21-Targeting-python.html

### 2. Reshaping tensor with view(-1, n)
- -1값이 들어갈 땐 n을 보고 reshape할 모양을 유추

### 3. Jupyter notebook extension toolkits
- notebook의 추가 기능 사용
- 참고https://www.slideshare.net/zzsza/10-jupyter-notebook

In [ ]:
a = 111