# Master Pytorch Chapter 1 : Tensor
https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/index.html

## Tensor
- multi-dimensional matrix containing elements of the single data type.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [3]:
x = torch.rand(5, 3)
x

tensor([[0.8421, 0.4011, 0.0730],
        [0.9500, 0.5464, 0.9201],
        [0.7289, 0.1193, 0.1721],
        [0.2919, 0.0003, 0.1513],
        [0.1146, 0.7739, 0.3087]])

In [4]:
x.size()

torch.Size([5, 3])

## Operations

In [5]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x, '\n')
print(y, '\n')
x + y

tensor([[0.8790, 0.3097, 0.2690],
        [0.9557, 0.6136, 0.9123],
        [0.2234, 0.8516, 0.2614],
        [0.2090, 0.0108, 0.8024],
        [0.6222, 0.5342, 0.7178]]) 

tensor([[0.2200, 0.8358, 0.2718],
        [0.1988, 0.3790, 0.9006],
        [0.0867, 0.1944, 0.6926],
        [0.2655, 0.5225, 0.2836],
        [0.0426, 0.9096, 0.8187]]) 



tensor([[1.0990, 1.1455, 0.5408],
        [1.1545, 0.9926, 1.8129],
        [0.3100, 1.0460, 0.9539],
        [0.4744, 0.5332, 1.0860],
        [0.6648, 1.4439, 1.5364]])

In [6]:
torch.add(x, y)

tensor([[1.0990, 1.1455, 0.5408],
        [1.1545, 0.9926, 1.8129],
        [0.3100, 1.0460, 0.9539],
        [0.4744, 0.5332, 1.0860],
        [0.6648, 1.4439, 1.5364]])

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
result

tensor([[1.0990, 1.1455, 0.5408],
        [1.1545, 0.9926, 1.8129],
        [0.3100, 1.0460, 0.9539],
        [0.4744, 0.5332, 1.0860],
        [0.6648, 1.4439, 1.5364]])

In [8]:
y.add(x)

tensor([[1.0990, 1.1455, 0.5408],
        [1.1545, 0.9926, 1.8129],
        [0.3100, 1.0460, 0.9539],
        [0.4744, 0.5332, 1.0860],
        [0.6648, 1.4439, 1.5364]])

## Indexing

In [9]:
x = torch.Tensor(5, 3)
x[:, 1]

tensor([1.5554e-43, 1.4574e-43, 1.4013e-43, 1.6816e-43, 1.6956e-43])

In [10]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [40]:
z = x.view(16, -1)
z

tensor([[-0.6950],
        [-0.0296],
        [ 2.2637],
        [ 0.1334],
        [ 0.4200],
        [ 1.8474],
        [ 0.6980],
        [-0.1209],
        [ 0.2104],
        [-1.3246],
        [ 0.9009],
        [ 0.0153],
        [-0.8967],
        [-0.8000],
        [ 1.2889],
        [-1.2440]])

## Convert Tensor&Numpy

In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # 주소를 공유하는 복사이기 때문에 a값이 변하면 같이 변한다.
np.add(a, 1, out=a)   # np.add를 사용하면 b값도 같이 변한다 <<< 이유가...(깊은 복사 vs 얕은 복사)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# New things I learned

### 1. from __future__ import print_function
- __future__를 통해 최신 python버젼의 function을 가져올 수 있다.
- 참고https://ddanggle.gitbooks.io/interpy-kr/ch21-Targeting-python.html

### 2. Reshaping tensor with view(-1, n)
- -1값이 들어갈 땐 n을 보고 reshape할 모양을 유추

### 3. Jupyter notebook extension toolkits
- notebook의 추가 기능 사용
- 참고https://www.slideshare.net/zzsza/10-jupyter-notebook