# Master Pytorch Chapter 2 : Autograd
https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/beginner/blitz/autograd_tutorial.html

## Autograd
- 자동미분을 제공한다.
- 실행-기반-정의(define-by-run) 프레임워크로, 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다.
- 역전파는 학습 과정마다 달란다.

### autograd.Variable 클라스
- .data, .grad, .grad_fn 등을 지원

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)
print('')
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)



In [4]:
z = y * y * 3
out = z.mean()
print(z)        
print('')        
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)

tensor(27., grad_fn=<MeanBackward1>)


In [5]:
a = torch.randn(2, 2)
a = ((a * 3) // (a - 1)) 
print(a.requires_grad, '\n')      

# .requires_grad_은 기존 Tensor에
# requuires_grad을 부여한다.  

a.requires_grad_(True)
print(a.requires_grad, '\n')

b = (a * a).sum()
print(b.grad_fn)

False 

True 



## 변화도(Gradient)
- 역전파 시도
- y = x + 2
- z = y * y * 3
- out = z.mean
![image](image/gradiant_example.png)

In [6]:
print(out)

out.backward()  # out = 3*y^2 = 3(x+2)^2
print(x.grad) # out에 대한 x의 미분값 출력(x = 1)

tensor(27., grad_fn=<MeanBackward1>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


# Example

In [7]:
x = torch.randn(3, requires_grad = True)

y = x * 2
i = 1
while y.data.norm() < 1000: # 각 원소에 절대값을 취한 후 더한 값(p-norm, p = 1)
    y = y * 2
    i += 1
print(i)
print(y)

10
tensor([   25.7213, -1520.9213,   310.9211], grad_fn=<MulBackward>)


In [8]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float) # .backward()는 결과가 1개일 때만 가능
y.backward(gradients) # 각 입력값에 따른 미분값 
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])


# Autograd 연산 기록 추적 정지
- with torch.no_grad(): 코드 블럭을 이용

In [9]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


# Questions
### 1. What is .norm()
- 여러 수치들의 다른 기준(길이, 무게 등)을 비교하기 위해 하나의 양수를 정하기 위한 정규화
- loss, normalization, generalization 등이 있다.
- .norm()의 default는 p-norm이다.
- p-norm의 경우에는![p-norm](image/p_norm2.png)
- 출처[개념]https://blog.naver.com/mobilemania/221134358627
- 출처[이미지]https://pytorch.org/docs/stable/torch.html