# Master Pytorch Chapter 2 : Autograd
https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/beginner/blitz/autograd_tutorial.html

## Autograd
- 자동미분을 제공한다.
- 실행-기반-정의(define-by-run) 프레임워크로, 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다.
- 역전파는 학습 과정마다 달란다.

### autograd.Variable 클라스
- .data, .grad, .grad_fn 등을 지원

In [42]:
import torch
from torch.autograd import Variable

In [33]:
# Make variable
x = Variable(torch.ones(2,2), requires_grad = True) # torch.Tensor와 모양이 다를게 없다.
y = x + 2 # 연산 실시
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [34]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


## 변화도(Gradient)
- 역전파 시도
- y = x + 2
- z = y * y * 3
- out = z.mean
![image](image/gradiant_example.png)

In [35]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [65]:
# example(이해가 잘 안 된다.)
x = torch.randn(3)
x = Variable(x, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([878.4826, 999.9269, 281.5692], grad_fn=<MulBackward>)


# Questions
### 1. What is .norm()
- 여러 수치들의 다른 기준(길이, 무게 등)을 비교하기 위해 하나의 양수를 정하기 위한 정규화
- loss, normalization, generalization 등이 있다.
- .norm()의 default는 p-norm이다.
- p-norm의 경우에는![p-norm](image/p_norm2.png)
- 출처[개념]https://blog.naver.com/mobilemania/221134358627
- 출처[이미지]https://pytorch.org/docs/stable/torch.html