# Mean Squared Error

In [29]:
import torch
import torch.nn as nn

print(torch.__version__)

y_data = torch.arange(1,10) # 정답
x_data = y_data + torch.rand(9) # 예측값
print(y_data)
print(x_data)

1.4.0
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1.7516, 2.5348, 3.4643, 4.5566, 5.3562, 6.6055, 7.2129, 8.2204, 9.3870])


In [35]:
MSE_loss = nn.MSELoss(reduction='mean')
MSE_loss(x_data, y_data)

tensor(0.2348)

In [31]:
MSE_loss = nn.MSELoss(reduction='none')
MSE_loss(x_data, y_data)

tensor([0.5649, 0.2861, 0.2156, 0.3098, 0.1269, 0.3666, 0.0453, 0.0486, 0.1497])

In [32]:
MSE_loss = nn.MSELoss(reduction='sum')
MSE_loss(x_data, y_data)

tensor(2.1134)

# Cross Entropy Error

In [118]:
x_data = torch.randn(3,5)
y_data = torch.empty(3, dtype=torch.long).random_(5)

print(x_data)
print(y_data)

tensor([[-0.8579,  1.2602, -2.3121,  1.4382, -0.2703],
        [ 1.5935,  0.3863,  0.4960, -1.4144,  0.8705],
        [-0.4117, -1.7978,  0.0361,  0.8761, -0.5714]])
tensor([3, 3, 1])


In [119]:
CEE_loss = nn.CrossEntropyLoss(reduction='mean')
CEE_loss(x_data, y_data)

tensor(2.6387)

In [120]:
CEE_loss = nn.CrossEntropyLoss(reduction='sum')
CEE_loss(x_data, y_data)

tensor(7.9161)

In [121]:
CEE_loss = nn.CrossEntropyLoss(reduction='none')
CEE_loss(x_data, y_data)

tensor([0.7618, 3.7814, 3.3728])

In [73]:
import numpy as np
import matplotlib.pyplot as plt

In [137]:
onehot = torch.zeros_like(x_data)
for i in range(x_data.shape[0]):
    idx = y_data[i]
    onehot[i][idx] = 1

onehot

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.]])