In [1]:
import torch
import torch.nn as nn

In [166]:
class mymodel(nn.Module):
    
    def __init__(self):
        super(mymodel, self).__init__()
        self.fc1 = nn.Linear(5,4)
        self.fc2 = nn.Linear(4,3)
        self.fc3 = nn.Linear(3,2)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        print('input(==x) =====', x)
        x1 = self.fc1(x)
        print('x1 =====', x1)
        x2 = self.dropout(x1)
        print('drop ====', x2)
        x3 = self.fc2(x2)
        print('x2 =====', x3)
        x4 = self.fc3(x3)
        print('x3 =====', x4)
        return x

In [137]:
class mymodel(nn.Module):
    
    def __init__(self):
        super(mymodel, self).__init__()
        self.fc1 = nn.Linear(5,4)
        self.fc2 = nn.Linear(4,3)
        self.fc3 = nn.Linear(3,2)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.dropout(x)
        
        x = self.fc2(x)       
        x = self.fc3(x)
        
        return x

In [167]:
model = mymodel()
model

mymodel(
  (fc1): Linear(in_features=5, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)

In [168]:
model.train()
a = torch.ones((5))
print(a)
model(a)

tensor([1., 1., 1., 1., 1.])
input(==x) ===== tensor([1., 1., 1., 1., 1.])
x1 ===== tensor([-0.2021, -0.8614, -0.1749, -0.6106], grad_fn=<AddBackward0>)
drop ==== tensor([-0.4041, -0.0000, -0.0000, -0.0000], grad_fn=<MulBackward0>)
x2 ===== tensor([ 0.6346, -0.1302, -0.0872], grad_fn=<AddBackward0>)
x3 ===== tensor([0.5077, 0.5231], grad_fn=<AddBackward0>)


tensor([1., 1., 1., 1., 1.])

In [143]:
model(a)

x ===== tensor([1., 1., 1., 1., 1.])
x1 ===== tensor([-0.2631,  1.0141,  0.3976, -0.5533], grad_fn=<AddBackward0>)
drop ==== tensor([-0.0000, 2.0282, 0.7952, -0.0000], grad_fn=<MulBackward0>)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5 and 4x3)

In [136]:
model.eval()

model(a)

x1 ===== tensor([ 0.0044, -0.1357, -0.0551, -0.6271], grad_fn=<AddBackward0>)
x2 ===== tensor([-0.2882,  0.0115, -0.1532], grad_fn=<AddBackward0>)
drop ==== tensor([-0.2882,  0.0115, -0.1532], grad_fn=<AddBackward0>)
x3 ===== tensor([-0.0929, -0.2413], grad_fn=<AddBackward0>)


tensor([-0.0929, -0.2413], grad_fn=<AddBackward0>)