In [1]:
import torch
import torch.nn as nn

In [152]:
class MyModel(nn.Module):
    
    def __init__(self):
        super(MyModel, self).__init__()
        
        self.fc1 = nn.Linear(4,3)
        self.fc2 = nn.Linear(3,2)
        self.dropout = nn.Dropout(0.4)
        
    def forward(self, x):
        x0 = x
        print('x0 == ', x0)
        
        x1 = self.fc1(x0)
        print('FC1 == ', x1)
        
        x2 = self.dropout(x1)
        print('Dropout == ', x2)
        
        x3 = self.fc2(x2)
        print('FC2 == ', x3)
        
        return x
    
model = MyModel()

In [153]:
a = torch.randn(1,4)
print(a)

tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])


### model.eval()
- Dropout이나 Batch Normalize 등을 off한다.

In [154]:
model.train()
model(a)

x0 ==  tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])
FC1 ==  tensor([[-0.2478, -0.4852,  0.7671]], grad_fn=<AddmmBackward>)
Dropout ==  tensor([[-0.4130, -0.0000,  0.0000]], grad_fn=<MulBackward0>)
FC2 ==  tensor([[ 0.3536, -0.7196]], grad_fn=<AddmmBackward>)


tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])

In [155]:
model.eval()
model(a)

x0 ==  tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])
FC1 ==  tensor([[-0.2478, -0.4852,  0.7671]], grad_fn=<AddmmBackward>)
Dropout ==  tensor([[-0.2478, -0.4852,  0.7671]], grad_fn=<AddmmBackward>)
FC2 ==  tensor([[ 0.1237, -0.5634]], grad_fn=<AddmmBackward>)


tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])

### torch.no_grad()
- 자동미분(Autograd)를 off한다.
- 메모리 사용 감소

In [158]:
with torch.no_grad():
    model.train()
    model(a)

x0 ==  tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])
FC1 ==  tensor([[-0.2478, -0.4852,  0.7671]])
Dropout ==  tensor([[-0.4130, -0.0000,  1.2786]])
FC2 ==  tensor([[-0.3012, -0.7093]])


In [159]:
with torch.no_grad():
    model.eval()
    model(a)

x0 ==  tensor([[ 0.8326,  0.6587, -1.3227,  0.4181]])
FC1 ==  tensor([[-0.2478, -0.4852,  0.7671]])
Dropout ==  tensor([[-0.2478, -0.4852,  0.7671]])
FC2 ==  tensor([[ 0.1237, -0.5634]])
