In [3]:
import torch
print(torch.__version__)

1.4.0


$y = \theta_1x + \theta_0$
<br>
<br>
$\theta_1 = 0.6, \theta_0 = -44$

대충 내가 가진 데이터로 계산을 해보니

In [209]:
import torch.nn as nn

simple_regression = nn.Linear(1, 1, bias=True)
print(simple_regression)

Linear(in_features=1, out_features=1, bias=True)


In [210]:
init_weight = simple_regression.weight
init_bias = simple_regression.bias

print(init_weight)
print(init_bias)

print(init_weight.size())
print(init_bias.size())

Parameter containing:
tensor([[-0.8308]], requires_grad=True)
Parameter containing:
tensor([0.7396], requires_grad=True)
torch.Size([1, 1])
torch.Size([1])


In [211]:
my_weight = torch.tensor([0.6666], dtype=torch.float).reshape_as(init_weight)
my_bias = torch.tensor([-44], dtype=torch.float).reshape_as(init_bias)

new_weight = nn.Parameter(my_weight)
new_bias = nn.Parameter(my_bias)

simple_regression.weight = new_weight
simple_regression.bias = new_bias

print(simple_regression.weight)
print(simple_regression.bias)

Parameter containing:
tensor([[0.6666]], requires_grad=True)
Parameter containing:
tensor([-44.], requires_grad=True)


In [212]:
cm = [174, 180, 169, 171]
kg = [ 72,  76,  65,  68]

data_x = torch.tensor(cm, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)
data_y = torch.tensor(kg, dtype=torch.float, requires_grad=False).reshape(len(cm), 1)

kg_prediction = simple_regression(data_x)

print(kg_prediction)
print(data_y.reshape_as(cm_prediction))

tensor([[71.9884],
        [75.9880],
        [68.6554],
        [69.9886]], grad_fn=<AddmmBackward>)
tensor([[72.],
        [76.],
        [65.],
        [68.]])
