# Dropout

In [1]:
import torch
import torch.nn as nn

class mymodel(nn.Module):
    
    def __init__(self):
        super(mymodel, self).__init__()
        self.fc1 = nn.Linear(5,4)
        self.fc2 = nn.Linear(4,3)
        self.fc3 = nn.Linear(3,2)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        print('input(==x) =====', x)
        
        x1 = self.fc1(x)      
        print('x1 =====', x1)
        
        x2 = self.dropout(x1)    
        print('drop ====', x2)
        
        x3 = self.fc2(x2)
        print('x2 =====', x3)
        
        x4 = self.fc3(x3)
        print('x3 =====', x4)
        
        return x
    
model = mymodel()
model

mymodel(
  (fc1): Linear(in_features=5, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
  (fc3): Linear(in_features=3, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)

In [2]:
model.train()
a = torch.ones((5))
print(a)

model(a)

tensor([1., 1., 1., 1., 1.])
input(==x) ===== tensor([1., 1., 1., 1., 1.])
x1 ===== tensor([ 0.6792,  0.0767, -0.1639, -0.4744], grad_fn=<AddBackward0>)
drop ==== tensor([ 0.0000,  0.1535, -0.3277, -0.0000], grad_fn=<MulBackward0>)
x2 ===== tensor([-0.2572,  0.0924,  0.3573], grad_fn=<AddBackward0>)
x3 ===== tensor([0.0434, 0.4619], grad_fn=<AddBackward0>)


tensor([1., 1., 1., 1., 1.])

In [3]:
model.eval()

model(a)

input(==x) ===== tensor([1., 1., 1., 1., 1.])
x1 ===== tensor([ 0.6792,  0.0767, -0.1639, -0.4744], grad_fn=<AddBackward0>)
drop ==== tensor([ 0.6792,  0.0767, -0.1639, -0.4744], grad_fn=<AddBackward0>)
x2 ===== tensor([-0.0987, -0.2586, -0.0511], grad_fn=<AddBackward0>)
x3 ===== tensor([-0.1455,  0.1071], grad_fn=<AddBackward0>)


tensor([1., 1., 1., 1., 1.])